### ISSUE TITLE
Provide more primitives to choose from when adding new meshes

### ISSUE THREAD

**Issue by abau** [abau/dilay#12]
... e.g., box and sphere. And make the number of initial subdivisions configurable.

**Comment by Protagores** [comment]
I would also add here that an option for using quadrilateral meshes instead of triangular would be quite nice too. MakeHuman for example uses quads rather than tris because of [a number of reasons](http://www.makehumancommunity.org/wiki/FAQ:Why_quadrilaterals%3F).

**Comment by abau** [comment]
Because of technical reasons there unfortunately won't be any sculpting support for quadrilateral meshes in Dilay. But maybe I can add some kind of retopology tool that generates quad meshes for export to other programs.

**Comment by abau** [comment]
Fixed in 1.6.0.
