### ISSUE TITLE
Stroking tessellation is not uniform and clean 

### ISSUE THREAD

**Issue by kakachiex2** [abau/dilay#13]
Wen brush stroking in dilay the surface is not clean and uniform compared to sculptris see image I don't know is this is a bug or an algorithm problem this leaves ugly surface when sculpting I hope you can fix it I'm heavy testing it to give you feedback to improve it 
![dilay ugly stroke](https://cloud.githubusercontent.com/assets/1762112/14578552/d66459d2-0358-11e6-8dce-bd98b298fbbb.jpg)

**Comment by abau** [comment]
I see your point. I will try to improve Dilay's subdivision procedure.

**Comment by kakachiex2** [comment]
Ohh nice news I'll be waiting

**Comment by kakachiex2** [comment]
Another problem is the center of symmetry if you see the picture in sculptris the center is intact in Dilay the center get tesselate

**Comment by abau** [comment]
> the center get tesselate

That's is what the *Sync* button is for: it mirrors the right side so that the mesh is perfectly symmetrical.

**Comment by kakachiex2** [comment]
Ohh I didn't know this thanks
