### ISSUE TITLE
Confused how DESTDIR works in packaging dilay for Linux distros?

### ISSUE THREAD

**Issue by ShadowKyogre** [abau/dilay#2]
I'm trying to package dilay for the Arch Linux User Repository (AUR), but I'm running into some trouble with the build process.

For instance, let's say that the files that need to be outputted should reside in `/tmp/testing`. Let's call that dir ${pkgdir}.

I tried running the following series of commands:
~~~~
qmake-qt5 -r PREFIX=/usr 
make release
make DESTDIR="${pkgdir}/" install
~~~~
Building works fine, but in the install stage, it attempts to forcefully put those binaries in /${PREFIX}

I also tried this:
~~~~
qmake-qt5 -r PREFIX=/usr DESTDIR="${pkgdir}/"
make release
make install
~~~~
Building works fine, but it fails on linking since during the build stage, ${pkgdir} isn't allowed to be written to.

So how would I modify these set of command to make it properly install to an arbitrary DESTDIR without failing on either `make` stage?

**Comment by abau** [comment]
> I'm trying to package dilay for the Arch Linux User Repository (AUR)

Thanks for your effort.

By passing `PREFIX=/tmp/testing` to `qmake`, Dilay's binary is installed to `/tmp/testing`:

```
$ qmake -r PREFIX=/tmp/testing
$ make release
$ make install

$ ls -R /tmp/testing/
/tmp/testing/:
bin

/tmp/testing/bin:
dilay
```

**Comment by ShadowKyogre** [comment]
@abau: Thanks! I've adjusted the PKGBUILD accordingly and it puts the binary in the expected place. Uploading to the AUR now.
