### ISSUE TITLE
Consider Chocolatey as a Windows distribution channel

### ISSUE THREAD

**Issue by kwill** [abau/dilay#26]
Chocolatey is a distribution tool for Windows applications, including many free software applications (for example, https://chocolatey.org/packages/pidgin). It allows an end-user to get application updates somewhat like using apt or yum on GNU/Linux.

Please consider it as a distribution channel for your Windows builds.

https://github.com/chocolatey/choco/wiki/ChocolateyFAQs
https://github.com/chocolatey/choco/wiki/Moderation

**Comment by fenollp** [comment]
This should help: https://gripdev.wordpress.com/2015/04/08/appveyor-github-and-chocolatey-automatically-build-your-project-and-publish-updates-it-to-chocolatey/

**Comment by abau** [comment]
Will look into this after the next release.

**Comment by kwill** [comment]
NB someone has just packaged it, the package is now in moderation - see https://github.com/chocolatey/chocolatey-package-requests/issues/12 and https://chocolatey.org/packages/dilay/1.5.0

Of course, having it be "officially" packaged would be great :D

**Comment by abau** [comment]
> NB someone has just packaged it

Nice.
