### ISSUE TITLE
convert win32 on UWP

### ISSUE THREAD

**Issue by duble0** [abau/dilay#28]
Hi! I'm Francesco Venuti, today I start a team of Windows lovers and developers without any scope of make money. We aimed of the scope to improve our OS...in the last year Windows 10 is improved a lot, for example today incorporate also a Linux Subsystem (WSL). Now Microsoft also engaged the mobile challenge, seems that they would change the concept of mobile computing...so not simply a smartphone, but real desktop experience that could run on ARM devices like tablets and smartphones (connected with a monitor).
We saw the preview of "Windows Colud edition", this could be the next Windows edition for mobile. Unfortunately for run win32 software on this edition, the software must be converted in UniversalWindowsPlatform app(but after conversion, software could run also on regular Windows 10 editions!...), if this could be a problem, you must consider the opportunities like: a larger user base that can give you feedback, as also know your work and start developing your software. Furthermore distributing your software on Microsoft Store, allowing direct update of your software to all users (or selected groups) and run the software into a kind of sandbox that don't compromise the OS if there are problems.
We tried the online tool made by Microsoft for convert win32 software to UWP app, so we start with Dilay, if you would use our work to start your experience on Microsoft Store we are pleased to give you all materials and information. For us is important start Cloud with a large amount of open source apps available for every one.
Anyway if you don't want publish on Microsoft Store we hope you are glad if we publish our converted Dilay app on the store....
Do you think that this opportunity is a good choose for you? 
Scuse me for poor English...😉

**Comment by duble0** [comment]
Edit.
"Hi! I'm Francesco Venuti, today I start a team of Windows lovers and developers without any scope of make money. We aimed of the scope to improve our OS...in the last year Windows 10 is improved a lot, for example today incorporate also a Linux Subsystem (WSL). Now Microsoft engaged the mobile challenge, seems that they would change the concept of mobile computing...so not simply a smartphone, but real desktop experience that could run on ARM devices like tablets and smartphones (connected with a PC)"

**Comment by abau** [comment]
> we hope you are glad if we publish our converted Dilay app on the store

Sure. As long as you respect the [license](https://github.com/abau/dilay/blob/master/LICENSE.txt) Dilay is published under, feel free to distribute Dilay in the Microsoft Store.
