### ISSUE TITLE
No Idea What This Error Means

### ISSUE THREAD

**Issue by esotericDisciple** [abau/dilay#29]
"
In file included from src/camera.cpp:9:0:
src/config.hpp: In member function ‘T Config::getFrom(const string&) const’:
src/config.hpp:35:24: error: no matching function for call to ‘Config::get(const string&) const’
         return get(path);
"

I tried building the fork from vincent-travel, but for some reason there isn't a way to report issues even though he seems to be the new owner of the project as he's the only one with any recent development activity. After fixing the renaming of the src/ to dilay/ issue, "make release" fails with the above output being the only error shown...

**Comment by abau** [comment]
Sorry, but as this is code from a fork, I've no idea what's missing there. Please try to contact the maintainer.
