### ISSUE TITLE
Consider adding scripting API

### ISSUE THREAD

**Issue by abau** [abau/dilay#30]
As this is a major feature, there are a few things to consider first:
- what's the purpose of this API, i.e., which of Dilay's functionalities should be accessible via the API?
- which language (Lua/Python/JavaScript/...) to use and why?
- ...

**Comment by obviouslyaman** [comment]
My recommendations:

* I'd use either Python or Ruby.  Python is the language used as Blender's scripting language.  Ruby is used as Sketchup's scripting language.  I'd probably go with Python, as Dilay seems like it would complement Blender well, and Blender developers already know Python (so could more easily contribute to Dilay). 

* In terms of what the API should do, perhaps it would be helpful to think about what the API would need to do to create some of the most popular Zbrush/Sketchup/Blender plugins.  For example, what would the API need to do to create a plugin for Dilay that does what the GoZ plugin does for Zbrush: 

http://www.creativebloq.com/features/the-10-best-zbrush-plugins

* One way to think about it would be to imagine that you were writing Dilay as a library that operates on .blend files with an extensive set of command-line tools like ImageMagick.  Dilay would then be a GUI interface to those command line tools, like the Converseen app is to ImageMagick:

https://www.youtube.com/watch?v=PNQycX8o1eA&t=184s 
http://converseen.fasterland.net/

The "API" would then be those command-line tools and their flags.  If they were written in C/C++, then they could be called by any scripting language that has C/C++ bindings similar to Imagemagick:

https://www.imagemagick.org/script/api.php

**Comment by abau** [comment]
I thought hard about this: despite that I'd love to implement a scripting API, I think such a feature is beyond the scope of Dilay as a side project I develop in my spare time.
