### ISSUE TITLE
toggle wireframe doesn't work

### ISSUE THREAD

**Issue by beew** [abau/dilay#35]
Hi, just discovered this wonderful software and gave it a spin. Every works except for toggle wireframe (w) Keeping pressing w and nothing happens. OS is Ubuntu 16.04 64 bit. dilay is from the latest master. I think my graphic card should be good enough.
Graphic card is intel iveybridge mobile
```
 glxinfo | grep OpenGL
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Ivybridge Mobile 
OpenGL core profile version string: 4.2 (Core Profile) Mesa 17.2.2 - padoka PPA
OpenGL core profile shading language version string: 4.20
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 17.2.2 - padoka PPA
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 17.2.2 - padoka PPA
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:
```
Am I missing something?

Please advise.

Thanks for the great work!

**Comment by abau** [comment]
> Keeping pressing w and nothing happens

Wireframe rendering is disabled if the GPU/driver doesn't support the `GL_EXT_geometry_shader4` extension. Could you post the output of `glxinfo | grep geometry_shader`?

> Thanks for the great work!

Thanks. Glad you like it!

**Comment by beew** [comment]
glxinfo | grep geometry_shader4

shows nothing, Guess my card is not qualified. : (

Thanks and keep up the good work!

**Comment by abau** [comment]
> Guess my card is not qualified. : (

Don't worry, I'm working on a fallback solution for wireframe rendering (see #25).
