### ISSUE TITLE
fail building 1.6

### ISSUE THREAD

**Issue by beew** [abau/dilay#38]
Hi, 

I was getting these build errors  for 1.6
```
src/camera.cpp:43:52: error: the type ‘const vec3 {aka const glm::tvec3<float, (glm::precision)0u>}’ of constexpr variable ‘up’ is not literal
     static constexpr glm::vec3 up (0.0f, 1.0f, 0.0f);
                                                    ^
In file included from /usr/include/glm/vec3.hpp:35:0,
                 from /usr/include/glm/gtc/matrix_transform.hpp:55,
                 from src/camera.cpp:5:
/usr/include/glm/detail/type_vec3.hpp:48:9: note: ‘glm::tvec3<float, (glm::precision)0u>’ is not literal because:
  struct tvec3
         ^
/usr/include/glm/detail/type_vec3.hpp:48:9: note:   ‘glm::tvec3<float, (glm::precision)0u>’ is not an aggregate, does not have a trivial default constructor, and has no constexpr constructor that is not a copy or move constructor
g++ -c -pipe -DDILAY_VERSION=\"1.6.0\" -DGLM_FORCE_RADIANS -O2 -DNDEBUG -fPIC -std=gnu++1y -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_OPENGLEXTENSIONS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -Isrc -I../../../opt/qt5/include -I../../../opt/qt5/include/QtOpenGL -I../../../opt/qt5/include/QtWidgets -I../../../opt/qt5/include/QtOpenGLExtensions -I../../../opt/qt5/include/QtGui -I../../../opt/qt5/include/QtXml -I../../../opt/qt5/include/QtCore -Imoc -isystem /usr/include/libdrm -I../../../opt/qt5/mkspecs/linux-g++ -o obj/src/dynamic/faces.o src/dynamic/faces.cpp
Makefile.Release:1241: recipe for target 'obj/src/camera.o' failed
make[2]: *** [obj/src/camera.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/bee/Downloads/dilay/lib'
Makefile:40: recipe for target 'release' failed
make[1]: *** [release] Error 2
make[1]: Leaving directory '/home/bee/Downloads/dilay/lib'
Makefile:507: recipe for target 'sub-lib-release' failed
make: *** [sub-lib-release] Error 2
```
OS is ubuntu 16.04.3 64 bits. Thanks

**Comment by abau** [comment]
Looks like your version of glm is too old. I tried to work around the limitiations of glm on Ubuntu 16.04, but then noticed that Ubuntu 16.04 only ships Qt 5.5.1. As Dilay 1.6 strictly requires Qt 5.9, I couldn't get it build on Ubuntu 16.04. Sorry.

**Comment by beew** [comment]
HI, I have installed a qt 5.9.2 locally and use d it to build dilay so  the qt requirement is fine.

**Comment by abau** [comment]
Interesting. Could you tell me how to install Qt 5.9.2 on Ubuntu 16.04? Did you compile it from source?

**Comment by beew** [comment]
Success!! I upgraded glm to 0.9.8.5 (built from source) now building dilay works! Thanks!

Yes I built qt-5.9.2 from source in my $HOME, idea is that qt4 is needed to compile some applications but if both qt-4 and 5 are installed in the system it always choose 5 and qt-chooser is pretty useless. 

These are basically my steps

Download qt from https://download.qt.io/archive/qt/5.9/5.9.2/
uncomptress
```
cd  /path/to/qt-folder
unset QTDIR
export PATH="$PWD/qtbase/bin:$PWD/qtrepotools/bin:$PATH"
./configure -prefix $HOME/opt/qt5 -confirm-license -opensource -qt-xcb -qt3d-profile-gl -glib -zlib -opengl -ffmpeg
make -j4
make install -j4
```
I then symlink qmake to /usr/bin/qmake-qt5

**Comment by abau** [comment]
Good work.

> Yes I built qt-5.9.2 from source in my $HOME

I see.

**Comment by beew** [comment]
Since you seem to use some fairly new libraries I am wondering if it would be feasible for you to provide a static linux build for people who are on older OS versions for their stability but may not want to compile the libraries from source. 

Thanks again!

**Comment by abau** [comment]
> if it would be feasible for you to provide a static linux build

[I will try to do this.](https://github.com/abau/dilay/issues/39)

**Comment by probonopd** [comment]
> Yes I built qt-5.9.2 from source in my $HOME

This may not be necessary if you use something like https://launchpad.net/~beineri/+archive/ubuntu/opt-qt592-trusty.

**Comment by probonopd** [comment]
@abau 
> Looks like your version of glm is too old. 

Which is the minimal version required?

**Comment by abau** [comment]
> Which is the minimal version required?

GLM 0.9.8. 

> And is there a PPA for Ubuntu trusty (the oldest currently still-supported LTS) available for a suitable version?

I have no idea (not a Ubuntu user).

> If not, could the requirement be lowered to such a version?

Yes I'm pretty sure that's doable, but I'm considering to add GLM as a Git submodule (cf. #42) to avoid depending on the GLM version shipped with the host OS.

**Comment by probonopd** [comment]
> Yes I'm pretty sure that's doable, but I'm considering to add GLM as a Git submodule (cf. #42) to avoid depending on the GLM version shipped with the host OS.

Wouldn't that add a _lot_ of build time?

**Comment by abau** [comment]
GLM is a header-only library, so build times shouldn't change.

**Comment by abau** [comment]
> but I'm considering to add GLM as a Git submodule

[Change of plans](https://github.com/abau/dilay/issues/42#issuecomment-343765284). The GLM dependeny on Ubuntu 14.04 shouldn't be an issue anymore when using Dilay's latest master.
