### ISSUE TITLE
Provide statically linked Linux build

### ISSUE THREAD

**Issue by abau** [abau/dilay#39]
- find out how to do that
- add corresponding make target
- provide build on website

**Comment by abau** [comment]
> find out how to do that

I failed, sorry.

**Comment by probonopd** [comment]
Maybe we can make an [AppImage](http://appimage.org/) instead?

Providing an AppImage would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by probonopd** [comment]
I've started work at https://github.com/probonopd/dilay/blob/patch-1/.travis.yml but the build fails at https://travis-ci.org/probonopd/dilay/builds/300972963#L666-L680:

```
     static constexpr glm::vec3 up (0.0f, 1.0f, 0.0f);
                                                    ^
In file included from /usr/include/glm/vec3.hpp:32:0,
                 from /usr/include/glm/gtc/matrix_transform.hpp:52,
                 from src/camera.cpp:5:
/usr/include/glm/detail/type_vec3.hpp:50:9: note: ‘glm::detail::tvec3<float, (glm::precision)0u>’ is not literal because:
  struct tvec3
         ^
/usr/include/glm/detail/type_vec3.hpp:50:9: note:   ‘glm::detail::tvec3<float, (glm::precision)0u>’ is not an aggregate, does not have a trivial default constructor, and has no constexpr constructor that is not a copy or move constructor
make[2]: *** [obj/src/camera.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/home/travis/build/probonopd/dilay/lib'
make[1]: *** [release] Error 2
make[1]: Leaving directory `/home/travis/build/probonopd/dilay/lib'
make: *** [sub-lib-release] Error 2
```

**Comment by probonopd** [comment]
An AppImage is available for testing at
https://github.com/probonopd/dilay/releases/

Please let me know whether it is working for you.

**Comment by abau** [comment]
Yes, seems to works fine. Very nice!
