### ISSUE TITLE
Add Floor plane

### ISSUE THREAD

**Issue by HellGate94** [abau/dilay#4]
a floor plane or grid would be great to get a better orientation sense and make sculpts align with the floor better (similar to how other 3d applications do it)

**Comment by abau** [comment]
Good idea; will implement this in the 1.5.0 release.

**Comment by kakachiex2** [comment]
Can you improve navigation like zbrush o sculptris for tablet
- Matcap would be good to have
- I like the sketch tool good work

**Comment by abau** [comment]
> Can you improve navigation like zbrush o sculptris for tablet

I don't own ZBrush so I don't know how the navigation works there but I will see what I can do regarding a Sculptris-like navigation...

> Matcap

Never heard of that before but this seems like a very useful feature. I will think about it. Thanks for the feedback.

**Comment by kakachiex2** [comment]
Matcap_is the material visualization based on 512x512 image check sculptris matcap and how it work Neobarrock too use Matcap and Blender.
Sculptris Matcap
![screenshot 2016-03-05 12 34 13](https://cloud.githubusercontent.com/assets/1762112/13548777/99f0ba22-e2ce-11e5-8915-472ff32d73b2.png)
In Neobarok
![lancelot](https://cloud.githubusercontent.com/assets/1762112/13548789/c2fd65c8-e2ce-11e5-89dd-eb4ae9a50f68.png)

**Comment by kakachiex2** [comment]
Neobarok is free you can download here
[http://neobarok.com/#](url)
