### ISSUE TITLE
"make install" fails

### ISSUE THREAD

**Issue by probonopd** [abau/dilay#43]
```
The command "make release -j$(nproc)" exited with 0.
$ make INSTALL_ROOT=appdir -j$(nproc) install ; find appdir/
(...)
make[2]: Nothing to be done for `install'.
```

Full build log:
https://travis-ci.org/probonopd/dilay/builds/301072191#L804

**Comment by abau** [comment]
Installing looks good to me: https://travis-ci.org/probonopd/dilay/builds/301072191#L817

The error appears to come from https://travis-ci.org/probonopd/dilay/builds/301072191#L821.

**Comment by probonopd** [comment]
#821 is below where the error happens. Does the following work for you, e.g., locally?

```
make INSTALL_ROOT=appdir -j$(nproc) install ; find appdir/
```

**Comment by abau** [comment]
The 
```
make[2]: Nothing to be done for `install'.
```
lines are no error: it just says that the for Dilay's `lib` and `test` submodules nothing needs to be done when installing (which is correct). The important part is

```
/opt/qt59/bin/qmake -install qinstall -exe ../../dilay/dilay appdir/usr/bin/dilay
strip appdir/usr/bin/dilay
```
which is the effect of running `make install` in Dilay's `app` submodule.

This is the error
```
find: `appdir/': No such file or directory
```

**Comment by abau** [comment]
Does the `appdir` directory exists on your machine before building/installing?

**Comment by probonopd** [comment]
> Does the `appdir` directory exist on your machine before building/installing?

No, it is supposed to be created by `make INSTALL_ROOT=appdir install` (this works for other applications).

**Comment by abau** [comment]
I see. Could you check if `appdir` was by any chance created inside Dilay's `app` directory?

**Comment by probonopd** [comment]
Indeed, that is the case. I assume this is not how it should be.

**Comment by abau** [comment]
I think it's because `make` changes directories before running the `install` target (see [here](https://travis-ci.org/probonopd/dilay/builds/301072191#L810)), and when having a relative `INSTALL_ROOT` path it won't create the target directory on the top-level.

**Comment by probonopd** [comment]
OK, not a big deal once one knows it. Don't spend time on this, as the workaround is easy on my side. Thanks!
