### ISSUE TITLE
Linux: Desktop file and icon missing

### ISSUE THREAD

**Issue by probonopd** [abau/dilay#44]
It would be great if `make install` would install `/usr/share/applications/dilay.desktop` and `/usr/share/icons/hicolor/scalable/apps/`. This is needed for the application to show up on the desktop. This can be achieved by changing the `.pro` file similar to https://github.com/probonopd/FeedTheMonkey/blob/master/FeedTheMonkey.pro.

**Comment by probonopd** [comment]
Reference:
https://travis-ci.org/probonopd/dilay/builds/301245280#L852

**Comment by probonopd** [comment]
This is currently blocking me to produce continuous builds (using Travis CI) to make an [AppImage](https://appimage.org/).

**Comment by probonopd** [comment]
If you can ping me once a release containing this fix is out, I can add your app to the AppImageHub central directory of available AppImages. Thanks!

**Comment by abau** [comment]
I will. Thanks.

**Comment by abau** [comment]
> If you can ping me once a release containing this fix is out

@probonopd I just pushed [release 1.7.0](https://github.com/abau/dilay/releases/tag/1.7.0).

**Comment by probonopd** [comment]
Thanks, new build is running, https://travis-ci.org/probonopd/dilay/builds/349959354 - let's see how it goes.

**Comment by probonopd** [comment]
Running into

```
src/time-delta.cpp:51:22: error: ‘defaultfloat’ is not a member of ‘std’
```

Reference: https://travis-ci.org/probonopd/dilay/jobs/349959407#L702
