### ISSUE TITLE
Dilay is dead??

### ISSUE THREAD

**Issue by beew** [abau/dilay#45]
I saw on the web site "Dilay is no longer being actively maintained and developed."

Is this the end?? Will development ever pick up again?

I am very sad, but thanks for the wonderful work. Hope you will continue working on it when you have the time, Linux really needs to have software like this working natively.

**Comment by abau** [comment]
> Will development ever pick up again?

I don't know yet.

> Linux really needs to have software like this working natively.

I think Blender provides most of what Dilay has to offer.

**Comment by abau** [comment]
> Will development ever pick up again?

@beew I just pushed [release 1.7.0](https://github.com/abau/dilay/releases/tag/1.7.0).

**Comment by beew** [comment]
Thanks!
