### ISSUE TITLE
Compile failure with clang-40

### ISSUE THREAD

**Issue by yurivict** [abau/dilay#46]
```
src/view/configuration.cpp:25:36: error: implicit instantiation of undefined template 'std::__1::array<std::__1::basic_string<char>, 1>'
  const std::array<std::string, 1> requireRestart ({{"editor/use-geometry-shader"}});
                                   ^
```
Version 1.6.1
FreeBSD 11.1

**Comment by abau** [comment]
Can't reproduce with clang 3.9.1 or 5.0.1 (not on FreeBSD though).

**Comment by yurivict** [comment]
Building with ```c++14```.

**Comment by abau** [comment]
[Yep, me too](https://github.com/abau/dilay/blob/5b2d3b19facc8c25b4710d1663c3c899f33db2aa/common.pri#L2).

**Comment by abau** [comment]
Could you try adding an `#include <array>` at the top of `lib/src/view/configuration.cpp` and see if it compiles then?

**Comment by yurivict** [comment]
> Could you try adding an #include <array> at the top of lib/src/view/configuration.cpp and see if it compiles then?

Yes, this makes it to build through.

**Comment by yurivict** [comment]
```#include <functional>``` is also missing in the same file.

**Comment by abau** [comment]
Ok, thanks. I'll fix this in the master branch.

**Comment by abau** [comment]
`#include <array>` was already in master, I've just added `#include <functional>`.

**Comment by yurivict** [comment]
Thanks!
