### ISSUE TITLE
Cannot compile; error: ‘defaultfloat’ is not a member of ‘std’

### ISSUE THREAD

**Issue by probonopd** [abau/dilay#48]
Running into

```
src/time-delta.cpp:51:22: error: ‘defaultfloat’ is not a member of ‘std’
```

Reference: https://travis-ci.org/probonopd/dilay/jobs/349959407#L702

**Comment by abau** [comment]
Looks like the platform you're compiling on requires an explicit `#include <ios>` in `time-delta.cpp`. I'll do a patch release.

**Comment by abau** [comment]
> Looks like the platform you're compiling on requires an explicit #include <ios>

No, the libstdc++ you're compiling with is too old. Use `g++5` or later. For example, [this](https://github.com/abau/dilay/blob/ba5df843bbd21c2dc8f90290dcf23d93dcc72268/unix/docker/ubuntu-trusty/Dockerfile) compiles fine on Trusty.

**Comment by probonopd** [comment]
Uh, this makes it more complicated as g++5 pulls in a "too new" libstdc++ (for trusty) but I will see what I can do. See https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#libstdcso6 for more information.
