### ISSUE TITLE
Freezing after clicking on sync

### ISSUE THREAD

**Issue by MihailTrajkovski** [abau/dilay#51]
![2018-04-20 10_17_29-youtube](https://user-images.githubusercontent.com/18718511/39039400-bd40dfd2-4485-11e8-9ff4-ef39dc3b08d6.png)
First I must say that I am a somewhat intermediate Blender user and  I find your zsphere functionality very useful, in fact way better and more intuitive than anything blender has to offer for creating base meshes. But I have two issues with it.
The first issue has been appearing lately when I've been trying to create a human base mesh(before that quadrupeds were working okay). Basically the problem is this: After some time my model loses sync, I click the button Sync, and the program freezes. Frankly this never happens at the beginning as I sometimes lose sync when i have a couple spheres and the sync still works. I've tried waiting once but even after 20 minutes it was still frozen.
(The log only contains system information, and I am on Nvidia 1060, on a Windows system, you can see a screenshot from the freeze above).
Also, the other issue I have is sometimes on the same place two spheres are created and I only find out after I've done quite some work and have to start big part of the process again, but i am not really sure if this is an issue on the program side, or on my side and i am clicking alt+left click twice without noticing.

**Comment by abau** [comment]
Thanks for your report. I'll look into both issues as soon as possible.

**Comment by abau** [comment]
> I click the button Sync, and the program freezes

This is a critical bug. I just published a [1.7.1](https://abau.org/dilay/download.html) bugfix release that's supposed to fix this. Thanks again for reporting this, @MihailTrajkovski .

> sometimes on the same place two spheres are created

I could not reproduce this yet, but based on your description I thought that it might be an handy feature to support attaching existing nodes (including their children) of a sketch to other nodes, e.g.,
```
   o              o
   |              |
   o       =>     o
  / \            /
 o   o          o
 |  /|\         |
 o o o o        o
               /|\
              o o o
```
This way one could easily fix situations like you've described. I'll open a separate issue for that.

**Comment by abau** [comment]
> I'll open a separate issue for that.

cf. #52

**Comment by MihailTrajkovski** [comment]
That's awesome. I will download and see if it works as it should as soon as I can.
And yes you are right about the other issue, reattaching existing nodes would definitely fix the problem.
