### ISSUE TITLE
Scaling

### ISSUE THREAD

**Issue by glenndebacker** [abau/dilay#58]
First of all this is simply brilliant finally something that feels as good as Sculptris (and which I can use on my mac and linux machine) 

There is only one thing that I seem to miss right now and is the way to scale a mesh when transforming and maybe clone a mesh e.g. eyes. Is this something that is planned ?

**Comment by abau** [comment]
> Is this something that is planned ?

Now it is. Thanks for your input!.

**Comment by glenndebacker** [comment]
No, problem!

**Comment by abau** [comment]
Done in 1.9.0.
