### ISSUE TITLE
I can not compile in Kubuntu Linux 15.04

### ISSUE THREAD

**Issue by YAFU** [abau/dilay#6]
Hello.
I get this problem when compiling (end lines):
============
In file included from /usr/include/glm/detail/func_trigonometric.inl:29:0,
                 from /usr/include/glm/detail/func_trigonometric.hpp:199,
                 from /usr/include/glm/trigonometric.hpp:32,
                 from /usr/include/glm/glm.hpp:108,
                 from src/view/double-slider.cpp:5:
/usr/include/glm/detail/func_exponential.inl:95:2: note: template<class T, glm::precision P> glm::detail::tvec4<T, P> glm::pow(const glm::detail::tvec4<T, P>&, const glm::detail::tvec4<T, P>&)
  VECTORIZE_VEC_VEC(pow)
  ^
/usr/include/glm/detail/func_exponential.inl:95:2: note:   template argument deduction/substitution failed:
src/view/double-slider.cpp:54:72: note:   mismatched types ‘const glm::detail::tvec4<T, P>’ and ‘const double’
                              * (min + (glm::pow (norm, 1.0f / float (o)) * (max - min))) 
                                                                        ^
src/view/double-slider.cpp:57:3: warning: control reaches end of non-void function [-Wreturn-type]
   }
   ^
Makefile.Release:1788: recipe for target 'obj/src/view/double-slider.o' failed
make[2]: *** [obj/src/view/double-slider.o] Error 1
make[2]: Leaving directory '/home/yafu/Descargas/dilay/lib'
Makefile:38: recipe for target 'release' failed
make[1]: *** [release] Error 2
make[1]: Leaving directory '/home/yafu/Descargas/dilay/lib'
Makefile:247: recipe for target 'sub-lib-release' failed
make: *** [sub-lib-release] Error 2
===========
This is the full output from the terminal:
http://www.pasteall.org/65963

**Comment by abau** [comment]
Which version of the glm library do you have installed?

**Comment by YAFU** [comment]
Hi.
It is 0.9.5.4 (from Ubuntu 15.04 official repo)

**Comment by YAFU** [comment]
I installed glm 0.9.7.2:
http://packages.ubuntu.com/xenial/libglm-dev

and it is working now, thanks!
