### ISSUE TITLE
Dilay generates invalid config file on system with russian locale

### ISSUE THREAD

**Issue by suhr** [abau/dilay#8]
For example:

```xml
<cursor-color type="color">
  <r type="float">1,000000</r>
  <g type="float">0,900000</g>
  <b type="float">0,900000</b>
</cursor-color>
```

While this is a correct format to *show* floating point numbers in Russian, it's an incorrect way to *store* them.

**Comment by abau** [comment]
Will be fixed in the 1.5.0 release. Thanks for reporting.
